import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./../public/static/css/globals.scss";
import dynamic from "next/dynamic";
import { AuthProvider } from "@providers/AuthProvider";
import { Guard } from "@guards/Guard";
const ReduxProvider = dynamic(() => import("@providers/ReduxProvider"), {
  ssr: false
});

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "English Words",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const title = metadata.title;
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <title>{title?.toString()}</title>
      </head>
      <body className={inter.className}>
        <ReduxProvider>
          <AuthProvider>
            <Guard>
              {children}
              <div id="portal" />
            </Guard>
          </AuthProvider>
        </ReduxProvider>
      </body>
    </html >
  );
}
